// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go/frame/dependency_injection/database/gorm"
	"go/frame/dependency_injection/handler"
	"go/frame/dependency_injection/service"
)

// Injectors from provider_injector.go:

// 定义Injector（一定要和Provider分开写，不能把Provider的定义也放到这个函数里）
func InitHandler() (*handler.GinHandler, func(), error) {
	db, cleanup := database.GetMysqlDB()
	gormNews := database.NewGormNews(db)
	recByTime := service.NewRecByTime(gormNews)
	ginHandler, cleanup2 := handler.NewGinHandler(recByTime)
	return ginHandler, func() {
		cleanup2()
		cleanup()
	}, nil
}
