// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: student_service.proto

package grpc_service

import (
	model "go/base/grpc/idl/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNo        int32                  `protobuf:"varint,4,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStudentRequest) Reset() {
	*x = QueryStudentRequest{}
	mi := &file_student_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStudentRequest) ProtoMessage() {}

func (x *QueryStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStudentRequest.ProtoReflect.Descriptor instead.
func (*QueryStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryStudentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryStudentRequest) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

type QueryStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*model.Student       `protobuf:"bytes,1,rep,name=Students,proto3" json:"Students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStudentResponse) Reset() {
	*x = QueryStudentResponse{}
	mi := &file_student_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStudentResponse) ProtoMessage() {}

func (x *QueryStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStudentResponse.ProtoReflect.Descriptor instead.
func (*QueryStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStudentResponse) GetStudents() []*model.Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type StudentIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=Ids,proto3" json:"Ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentIds) Reset() {
	*x = StudentIds{}
	mi := &file_student_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentIds) ProtoMessage() {}

func (x *StudentIds) ProtoReflect() protoreflect.Message {
	mi := &file_student_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentIds.ProtoReflect.Descriptor instead.
func (*StudentIds) Descriptor() ([]byte, []int) {
	return file_student_service_proto_rawDescGZIP(), []int{2}
}

func (x *StudentIds) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StudentId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentId) Reset() {
	*x = StudentId{}
	mi := &file_student_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentId) ProtoMessage() {}

func (x *StudentId) ProtoReflect() protoreflect.Message {
	mi := &file_student_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentId.ProtoReflect.Descriptor instead.
func (*StudentId) Descriptor() ([]byte, []int) {
	return file_student_service_proto_rawDescGZIP(), []int{3}
}

func (x *StudentId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_student_service_proto protoreflect.FileDescriptor

const file_student_service_proto_rawDesc = "" +
	"\n" +
	"\x15student_service.proto\x12\vidl.service\x1a\x13model/student.proto\"m\n" +
	"\x13QueryStudentRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\x05R\bPageSize\x12\x16\n" +
	"\x06PageNo\x18\x04 \x01(\x05R\x06PageNo\"F\n" +
	"\x14QueryStudentResponse\x12.\n" +
	"\bStudents\x18\x01 \x03(\v2\x12.idl.model.studentR\bStudents\"\x1e\n" +
	"\n" +
	"StudentIds\x12\x10\n" +
	"\x03Ids\x18\x01 \x03(\x03R\x03Ids\"\x1b\n" +
	"\tStudentId\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id2\xfe\x02\n" +
	"\astudent\x12S\n" +
	"\fQueryStudent\x12 .idl.service.QueryStudentRequest\x1a!.idl.service.QueryStudentResponse\x12L\n" +
	"\x0eQueryStudents1\x12\x17.idl.service.StudentIds\x1a!.idl.service.QueryStudentResponse\x12?\n" +
	"\x0eQueryStudents2\x12\x17.idl.service.StudentIds\x1a\x12.idl.model.student0\x01\x12M\n" +
	"\x0eQueryStudents3\x12\x16.idl.service.StudentId\x1a!.idl.service.QueryStudentResponse(\x01\x12@\n" +
	"\x0eQueryStudents4\x12\x16.idl.service.StudentId\x1a\x12.idl.model.student(\x010\x01B\x1aZ\x18idl/service;grpc_serviceb\x06proto3"

var (
	file_student_service_proto_rawDescOnce sync.Once
	file_student_service_proto_rawDescData []byte
)

func file_student_service_proto_rawDescGZIP() []byte {
	file_student_service_proto_rawDescOnce.Do(func() {
		file_student_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_service_proto_rawDesc), len(file_student_service_proto_rawDesc)))
	})
	return file_student_service_proto_rawDescData
}

var file_student_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_student_service_proto_goTypes = []any{
	(*QueryStudentRequest)(nil),  // 0: idl.service.QueryStudentRequest
	(*QueryStudentResponse)(nil), // 1: idl.service.QueryStudentResponse
	(*StudentIds)(nil),           // 2: idl.service.StudentIds
	(*StudentId)(nil),            // 3: idl.service.StudentId
	(*model.Student)(nil),        // 4: idl.model.student
}
var file_student_service_proto_depIdxs = []int32{
	4, // 0: idl.service.QueryStudentResponse.Students:type_name -> idl.model.student
	0, // 1: idl.service.student.QueryStudent:input_type -> idl.service.QueryStudentRequest
	2, // 2: idl.service.student.QueryStudents1:input_type -> idl.service.StudentIds
	2, // 3: idl.service.student.QueryStudents2:input_type -> idl.service.StudentIds
	3, // 4: idl.service.student.QueryStudents3:input_type -> idl.service.StudentId
	3, // 5: idl.service.student.QueryStudents4:input_type -> idl.service.StudentId
	1, // 6: idl.service.student.QueryStudent:output_type -> idl.service.QueryStudentResponse
	1, // 7: idl.service.student.QueryStudents1:output_type -> idl.service.QueryStudentResponse
	4, // 8: idl.service.student.QueryStudents2:output_type -> idl.model.student
	1, // 9: idl.service.student.QueryStudents3:output_type -> idl.service.QueryStudentResponse
	4, // 10: idl.service.student.QueryStudents4:output_type -> idl.model.student
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_student_service_proto_init() }
func file_student_service_proto_init() {
	if File_student_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_service_proto_rawDesc), len(file_student_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_service_proto_goTypes,
		DependencyIndexes: file_student_service_proto_depIdxs,
		MessageInfos:      file_student_service_proto_msgTypes,
	}.Build()
	File_student_service_proto = out.File
	file_student_service_proto_goTypes = nil
	file_student_service_proto_depIdxs = nil
}
