// Code generated by Kitex v0.14.1. DO NOT EDIT.

package math

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	math_service "my_kitex/kitex_gen/math_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Add(ctx context.Context, Req *math_service.AddRequest, callOptions ...callopt.Option) (r *math_service.AddResponse, err error)
	Sub(ctx context.Context, Req *math_service.SubRequest, callOptions ...callopt.Option) (r *math_service.SubResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMathClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMathClient struct {
	*kClient
}

func (p *kMathClient) Add(ctx context.Context, Req *math_service.AddRequest, callOptions ...callopt.Option) (r *math_service.AddResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, Req)
}

func (p *kMathClient) Sub(ctx context.Context, Req *math_service.SubRequest, callOptions ...callopt.Option) (r *math_service.SubResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sub(ctx, Req)
}
