// Code generated by Kitex v0.14.1. DO NOT EDIT.
package math

import (
	server "github.com/cloudwego/kitex/server"
	math_service "my_kitex/kitex_gen/math_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler math_service.Math, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler math_service.Math, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
